Dev
poshyvailo/rg_courses_bookstore pull request #1
Opened 2018-03-05 09:18 UTC by poshyvailo

2018-03-07 18:07 UTC, kirillshevch commented on app/controllers/concerns/order_operation.rb
> +      order_from_customer || order_from_cookie || new_order
`current_order ||= order_from_customer || order_from_cookie || new_order`

2018-03-07 18:07 UTC, kirillshevch commented on app/controllers/carts_controller.rb
> +  include OrderOperation
we don't need it here

2018-03-07 18:07 UTC, kirillshevch commented on app/controllers/checkout_controller.rb
> +end
should be refactored with service objects

2018-04-22 11:07 UTC, bezrukavyi requested changes
https://docs.google.com/document/d/1sj7zszZf4g3l4xXYa1V6QFl5w0uQpIk9YvfuoVF09Ls/edit?usp=sharing

2018-04-22 11:07 UTC, bezrukavyi commented on app/assets/javascripts/inputmask/bindings/inputmask.binding.min.js
> +!function(a){"function"==typeof define&&define.amd?define(["jquery","../inputmask","../global/document"],a):"object"==typeof exports?module.exports=a(require("jquery"),require("../inputmask"),require
Внешние библиотеки должны храниться в директории `vendor`

2018-04-22 11:07 UTC, bezrukavyi commented on app/commands/add_cart_item.rb
> +    book_in_order? ? change_item_quantity : create_new_order_item
Подозреваю что если `Book.find_by id: params[:book_id]` вернет `nil` то клиенту придет статус 500

2018-04-22 11:07 UTC, bezrukavyi commented on app/commands/add_cart_item.rb
> +    @order.order_items.map(&:book_id).include? @book.id
Думаю не лучшая идея вызывать `map` на коллекции. Можно написать более оптимальный вариант:
```ruby
@order.order_items.where(book: @book).exists?
```

2018-04-22 11:07 UTC, bezrukavyi commented on app/commands/add_cart_item.rb
> +  def find_book_in_order
Можно избавиться от предыдущего метода (`book_in_order?`) если проверять на наличие результата метода `find_book_in_order `

2018-04-22 11:07 UTC, bezrukavyi commented on app/commands/add_cart_item.rb
> +    @order.save(validate: false)
Мне кажется отключение валидации не обоснована

2018-04-22 11:07 UTC, bezrukavyi commented on app/commands/customer_update_settings.rb
> +      broadcast :ok, t('settings.flash.email_changed')
методы
- update_billing_address
- update_shipping_address
- change_email
- change_password

 возращают broadcast :ok и `какой-то успешный месседж` и fail без месседжа 

Думаю надо добавить месседжи для ошибок и сделать все это более DRY

2018-04-22 11:07 UTC, bezrukavyi commented on app/commands/customer_update_settings.rb
> +  def change_password
Буква S из аббревиатуры [SOLID](https://robots.thoughtbot.com/back-to-basics-solid)  говорит о том что класс должен иметь единый прицип ответственности. А здесь мы и адреса заполняем и пароли юзеру меняем.

2018-04-22 11:07 UTC, bezrukavyi commented on app/commands/update_cart_item.rb
> +    delete_item if @params.has_key? :delete
Думаю за удаление должен отвечать отдельный сервис, который бы тригерился по HTTP-методу DELETE в экшене destroy контроллера OrderItems

2018-04-22 11:07 UTC, bezrukavyi commented on app/commands/update_cart_item.rb
> +    broadcast :ok
Получается если я передам в URL запроса get-параметры  `?delete=true&plus=true&minus=true`,  то цепочка будет следующая:
`удалить order_item` => `инкрементировать order_item` => `декрементировать order_item`. 
Скорей всего что-то лишнее

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/book_controller.rb
> +  decorates_assigned :review
Не смог найти место где определяется инстансная переменная `review`

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/book_controller.rb
> +    @book = @book.decorate
В [документации](https://github.com/drapergem/draper#when-to-decorate-objects) указано что `decorates_assigned` создает хелпер возвращающий истанс-декоратор (`book`). Для чего тогда переопределять переменную `@book`

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/book_controller.rb
> +
Думаю метод `update` должен как минимум обновлять что-то

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/carts_controller.rb
> +    coupon = Coupon.find_by name: params[:coupon].upcase
Лучше избавляться от излишней логики в контроллерах. С этой задачей отлично справляются [Service Objects](https://www.sitepoint.com/7-design-patterns-to-refactor-mvc-components-in-rails)

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/catalogs_controller.rb
> +  decorates_assigned :book
На нашел переменную `@book`

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/checkout_controller.rb
> +class CheckoutController < ApplicationController
Наверное этот контроллер можно избавить от лишней логики

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/checkout_controller.rb
> +    cookies.delete :order_id
Нашел метод `delete_order_from_cookie`, который делает тоже самое

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/concerns/order_concern.rb
> +        current_order.save!(validate: false)
`save!` вызовит ошибку если не получилось сохранить сущность(например из-за невалдиных данных), а `validate: false` отменяте валидацию. Думаю что-то лишнее

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/concerns/order_item_concern.rb
> +      @order_items = current_order.order_items
Лучше использовать мемоизацию
```ruby
@order_items ||= current_order.order_items
```

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/customers/omniauth_callbacks_controller.rb
> +    redirect_to root_path
Пользователю было бы удобнее получить дать знать о том что аутентификации через соцсеть провалилась

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/order_item_controller.rb
> +    @params = params
В этом методе действительно есть необходимость?

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/reviews_controller.rb
> +      redirect_to catalog_book_path(@book), notice: 'Review added'
i18n

2018-04-22 11:07 UTC, bezrukavyi commented on app/decorators/book_decorator.rb
> +    truncate(description, length: 500, separator: ' ', omission: '... ') { link_to "View More", "#" }
i18n

2018-04-22 11:07 UTC, bezrukavyi commented on app/models/ability.rb
> +    # elsif customer.confirmed_at
Комментари ввиде неиспользуемого кода лучше убирать

2018-04-22 11:07 UTC, bezrukavyi commented on app/models/ability.rb
> +      can :manage, Order
Пользователь может менеджить любые Order и OrderItem?

2018-04-22 11:07 UTC, bezrukavyi commented on app/models/book.rb
> +  scope :best_seller, -> { order("RANDOM()").includes(:authors).limit(4) }
Разве `best_seller` не определяется по количествую проданных книг?

2018-04-22 11:07 UTC, bezrukavyi commented on app/models/concerns/sortable.rb
> +        results = results.public_send(key, value) if value.present?
Желательно добавить проверку раз в sorting_params могут приходить значения из get параметров

2018-04-22 11:07 UTC, bezrukavyi commented on app/models/credit_card.rb
> +    return date if date.is_a? Time
Почему метод writer ничего не запишет если аргументом придет экземпляр класса Time?

2018-04-22 11:07 UTC, bezrukavyi commented on app/models/customer.rb
> +    super() || build_billing_address
Можно вызывать просто `super`. Но желательно не переопределять методы которые опредляются с помощью relation методов(`belongs_to :billing_address`), так как это не явно в использовании

2018-04-22 11:07 UTC, bezrukavyi commented on app/models/order.rb
> +      super() || public_send("build_#{method}")
Тоже самое что в предыдущем комментарии

2018-04-22 11:07 UTC, bezrukavyi commented on app/models/review.rb
> +    self.verified = customer.orders.find_book(book).empty? ? false : true
Можно сделать проще:
```ruby
self.verified = customer.orders.find_book(book).exists?
```

2018-04-22 11:07 UTC, bezrukavyi commented on app/uploaders/image_uploader.rb
> +  storage :file
Рекомендую озанкомиться с [fog](https://github.com/fog/fog) и [S3](https://aws.amazon.com/s3)

2018-04-22 11:07 UTC, bezrukavyi commented on config/initializers/devise.rb
> +  config.secret_key = '3b68d0d1f14f9cfbf42b3640ab997d5bb99b7fa80cfed7da9ed54f6c872ce592bd63b91de858b2376b3d24f135ad54717d9e18bdcaab5ea1542792da1240b7a6'
Этого не должно быть в публичном доступе

2018-04-22 11:07 UTC, bezrukavyi commented on config/initializers/devise.rb
> +  config.mailer_sender = 'bookstore@office.com'
Лучше использовать ENV переменные

2018-04-22 11:07 UTC, bezrukavyi commented on spec/factories/authors.rb
> +    # factory :author_with_books do
Комментарии не использованного кода лучше удалять

2018-04-22 11:07 UTC, bezrukavyi commented on spec/features/checkout/address_spec.rb
> +        fill_in "order_#{type}_address_attributes_phone", with: address.phone
Думаю заполнение полей адреса можно вынести в хелперы

2018-04-22 11:07 UTC, bezrukavyi commented on spec/models/book_spec.rb
> +  # let!(:book_one) { create(:book, title: "A", price: 1) }
Комментарии :(

2018-04-22 11:07 UTC, bezrukavyi commented on app/admin/books.rb
> +      f.input :author_ids, as: :select, input_html: { multiple: true }, collection: Author.all.collect {|author| ["#{author.firstname} #{author.lastname}", author.id] }
Думаю лучше вынести это в active admin хелперы:

```ruby
Author.select(:id, :firstname, :lastname).collect { |author| ["#{author.firstname} #{author.lastname}", author.id] }
```

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/catalogs_controller.rb
> +    @books = Book.includes(:authors).sorting(params.slice(:price_sort, :created_sort)).page(params[:page]).decorate
А что бы на это сказал rubocop?

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/category_controller.rb
> +    @books = Category.find(params[:id]).books.includes(:authors).sorting(params.slice(:price_sort, :created_sort)).page(params[:page]).decorate
Тоже что и в `CatalogsController`, может вынести повторяющуюся логику в одно место? Может даже в [Query Objects](https://www.sitepoint.com/7-design-patterns-to-refactor-mvc-components-in-rails)

2018-04-22 11:07 UTC, bezrukavyi commented on app/controllers/customers/registrations_controller.rb
> +    yield resource if block_given?
Не нашел где вызывается destroy с блоком

2018-04-22 11:07 UTC, bezrukavyi commented on app/decorators/book_decorator.rb
> +
Что-то мне подсказывает что этот метод не используются

2018-04-22 11:07 UTC, bezrukavyi commented on app/decorators/order_decorator.rb
> +    sub_total + delivery_cost.to_f - coupon_discount.to_f
А для чего вызывать на стоимости заказа `to_f` если мы используется операции прибавления и вычитания?

2018-04-22 11:07 UTC, bezrukavyi commented on app/models/customer.rb
> +  def self.new_with_session(params, session)
Не думаю что модели лучше место для работы с сессией. Может вынести это в Service Object и уже в него передавать все необходимые параметры?

2018-04-22 11:07 UTC, bezrukavyi commented on app/models/customer.rb
> +      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
Rubocop бы сказал что не лучшая идея определять переменные в условных конструкциях

2018-04-22 11:07 UTC, bezrukavyi commented on app/views/book/_images.html.haml
> +  -#  %a.img-link{href: "#"}
Этот партил нигде не используется?

2019-02-25 20:47 UTC, closed without merging

2019-02-26 07:54 UTC, bezrukavyi commented
Так и не пофиксил 🙁